### PR TITLE
Fix SelectPresetWidget context menu outside of items

### PR DESCRIPTION
**Pull request by henriquegemignani**

### CODE REVIEW

**Review by duncathan — APPROVED** [review]
what was the issue, here?

**Comment by henriquegemignani** [comment]
https://github.com/randovania/randovania/pull/4903/files#diff-21a9b33a4205ae814f34b2141e90ea929bf642eb03aec94164693bfcfd4329a2R81-R84
The type hints are not a lie :P

**Comment by duncathan** [comment]
yeah, I see the fix, but I'm curious what problems it was causing

**Comment by henriquegemignani** [comment]
> yeah, I see the fix, but I'm curious what problems it was causing

If you right click outside of items, the context menu is displayed but doesn't have a preset.

**Pull request merged**
