### PR TITLE
Prime 1 racetime.gg integration

### LINKED ISSUE #1434: Racetime.gg integration: Permalink for in progress race imported instead of selected open race.

### PR DESCRIPTION
**Pull request by EthanArmbrust**
Implements #2046  
Adds support for Prime 1 in the racetime.gg browser. A checkbox filter for each supported game allows users to filter out unwanted games.
racetime_browser_update

This also fixes #1434 and updates _TEST_RESPONSE to include this edge case.

### CODE REVIEW

**Comment by henriquegemignani** [comment]
... I could've waited before making 3.0.3, oh well.

Do you mind rebasing this on top of the `stable` branch, so we can release it as 3.0.4?

**Comment by EthanArmbrust** [comment]
This is kind of messy with since I merged main into this branch, any tips for rebasing?

**Comment by henriquegemignani** [comment]
Do an interactive rebase and exclude any commits you don't care about. Keep a copy of the branch so you can easily try again without having to look at reflog.

**Comment by EthanArmbrust** [comment]
Hopefully that didn't completely ruin everything...

**Pull request merged**
