### PR TITLE
Dread: Use lock override on door in Artaria with both Super and Charge

### PR DESCRIPTION
**Pull request by Tyranisaur**

### CODE REVIEW

**Review by XenoWars — APPROVED** [review]

**Comment by Tyranisaur** [comment]
How many failures until we give up and merge directly?

**Comment by ThanatosGit** [comment]
I thought it's just a random error again and mindlessly pushed the button while doing something completly different but looking into the queue it's actually a problem?

**Comment by duncathan** [comment]
> I thought it's just a random error again and mindlessly pushed the button while doing something completly different but looking into the queue it's actually a problem?

it's the same GUI test that usually fails randomly? I think we're just getting ridiculously unlucky

**Comment by ThanatosGit** [comment]
> > I thought it's just a random error again and mindlessly pushed the button while doing something completly different but looking into the queue it's actually a problem?
> 
> it's the same GUI test that usually fails randomly? I think we're just getting ridiculously unlucky

The executable is not even building which is before the tests ofc https://github.com/randovania/randovania/actions/runs/10237502538/job/28320882361

**Comment by duncathan** [comment]
...what. that wasn't happening yesterday LOL

**Comment by ThanatosGit** [comment]
Guess something wrong with a new package? ...and on "none executable" tests (which is also not the usual flaky tests stuff):
```
=========================== short test summary info ===========================
FAILED test/gui/test_tracker_window.py::test_apply_previous_state[False] - ImportError: DLL load failed while importing _c_internal_utils: The specified module could not be found.
FAILED test/gui/test_tracker_window.py::test_apply_previous_state[True] - ImportError: DLL load failed while importing _c_internal_utils: The specified module could not be found.
FAILED test/gui/test_tracker_window.py::test_load_multi_starting_location - ImportError: DLL load failed while importing _c_internal_utils: The specified module could not be found.
FAILED test/gui/test_tracker_window.py::test_load_single_starting_location - ImportError: DLL load failed while importing _c_internal_utils: The specified module could not be found.
FAILED test/gui/test_tracker_window.py::test_preset_without_starting_location - ImportError: DLL load failed while importing _c_internal_utils: The specified module could not be found.
============ 5 failed, 5623 passed, 3 skipped in 227.38s (0:03:47) ============
```

**Pull request merged**
