### PR TITLE
Prime 1: Have artifacts be static assignments instead of being placed by generator

### PR DESCRIPTION
**Pull request by Miepee**
There was some concern that placing artifacts by the generator lead to them being placed too soon and/or too easily accessible
This is thus an attempt to place them statically, before any generation takes place.

Obviously needs heavy testing. Should maybe also be gated behind an option too.

### CODE REVIEW

**Comment by Samuel6710** [comment]
Should be an option imo.

**Comment by henriquegemignani** [comment]
This has the massive disadvantage of being local only.
Also it should handle, in some way or form, if certain locations are inaccessible, like excluded pickups, starting location, elevator distribution.

**Comment by duncathan** [comment]
I'm not totally convinced this will provide better outcomes than messing with the minimum actions for artifact placement feature tbh

**Comment by Miepee** [comment]
Closing as not deemed useful. Idea could be revisited, if there's a generic implementation of it accessible.

**Pull request closed without merging**
