### PR TITLE
Add toggle for warp to start to Dread

### PR DESCRIPTION
**Pull request by MayberryZoom**
Adds a new boolean to Dread's preset configuration, migrates presets from v73, and adds the warp to start boolean to Dread's PDF. If I didn't mess anything up, this should be entirely hidden from users and only accessible by manually editing an rdvgame.

### CODE REVIEW

**Review by ThanatosGit — CHANGES_REQUESTED** [review]
Iirc the tests look for a cosmetic json file and if not found, it takes the default cosmetics.
I don't see a reason why the cosmetic files now needs to be part of this PR as it shouldn't change anything in the cosmetics.

**Comment by MayberryZoom** [comment]
> Iirc the tests look for a cosmetic json file and if not found, it takes the default cosmetics. I don't see a reason why the cosmetic files now needs to be part of this PR as it shouldn't change anything in the cosmetics.

So I should remove the cosmetic files? I was told to include them.

**Comment by Miepee** [comment]
The edited RDVGames shouldve been included, not the cosmetic files.

**Comment by ThanatosGit** [comment]
> The edited RDVGames shouldve been included, not the cosmetic files.

No. Rdvgames go through migration. The changed patcher json is sufficient.

**Comment by Miepee** [comment]
erh, meant that, thanks for correction xP

**Review by ThanatosGit — APPROVED** [review]

**Pull request merged**
