### PR TITLE
Add option to create new preset

### PR DESCRIPTION
**Pull request by Miepee**
Partly addresses #6183 
grafik

Probably has mypy errors and likely needs test adjustments.

### CODE REVIEW

**Comment by ThanatosGit** [comment]
What about this thing here and about the idea to not hide it in the right click menu like mentioned  in https://github.com/randovania/randovania/issues/6183 ?

**Comment by Miepee** [comment]
I wanted to have both: an entry in the context menu, and a button.

**Review by duncathan — COMMENTED** [review]
I would rather have both Import and Create New as proper buttons, and leave the context menu for actions on specific presets tbh

**Comment by Miepee** [comment]
Hmm, considering how (IIRC) there are already quite a few exceptions solely to handle the import action, yeah.

**Comment by Miepee** [comment]
Gonna close this PR for now. The next PR that wants to address the issue should make a button that creates a new preset and not have special handling for it like the import action currently does.

**Pull request closed without merging**
