### PR TITLE
Add MSR exporter and activate it

### PR DESCRIPTION
**Pull request by ThanatosGit**

### CODE REVIEW

**Comment by Miepee** [comment]
any specific reason why it's draft?

**Comment by ThanatosGit** [comment]
Well, if you want the honest answer: If I open it without a draft and requesting review, I would get immediate review for tests, mypy etc. So, I opened it as a draft first to check it and now I get a message why it is a draft :(

**Comment by ThanatosGit** [comment]
`module is installed, but missing library stubs or py.typed marker [import-untyped]` do we actually provide these for patcher? Don't think we have that for odr either

**Review by Miepee — APPROVED** [review]
lgtm. would be nice to get the type hints complains away, but no idea what's involved to do that.

**Pull request merged**
