### PR TITLE
Dread: Add Cross Bomb alternative for Flash Gates

### PR DESCRIPTION
**Pull request by XenoWars**

### CODE REVIEW

**Comment by henriquegemignani** [comment]
Does this work for every single flash shift gate in the game?

**Comment by XenoWars** [comment]
Every flash gate except the one at the top of Burenia, but one is not a door so it would not apply to it. There's also only 5 flash doors in the game surprisingly enough.

**Comment by henriquegemignani** [comment]
Oh! It definitely should be Knowledge Beginner to use cross bombs.

**Comment by XenoWars** [comment]
Is there a method in the editor to edit weaknesses?

**Comment by dyceron** [comment]
You can just say Flash Shift or (Lay Cross Bomb and Knowledge (Beginner)).

Also, why are they called "Phase Shift" doors in the header? lol

**Comment by henriquegemignani** [comment]
> You can just say Flash Shift or (Lay Cross Bomb and Knowledge (Beginner)).
> 
> Also, why are they called "Phase Shift" doors in the header? lol

Internal name for these doors.

**Pull request merged**
