### PR TITLE
DRAFT: copy on game details

### PR DESCRIPTION
**Pull request by Miepee**
Someone please check this branch out and report how the button looks on non-linux.

Here's how it looks for me:
grafik

Current known issue that the icon does not change color on light theme:
grafik

### CODE REVIEW

**Comment by ThanatosGit** [comment]
> does not change color on light theme

It's the opposite on windows
image
image

**Comment by Miepee** [comment]
Is your system/Windows theme light or dark?
For me in the above screenshots, I was on dark mode. If I switch my system theme to light mode (I have never seen my desktop blinding me so much before), I get the same results as you:
image
image

**Comment by ThanatosGit** [comment]
> Is your system/Windows theme light or dark?

What is this question 😛?
I use "Dunkel" on Windows 10 in these settings here and everything else like Github etc. also appears in dark mode. Should be the system settings. Just saying this because windows is good in hiding the same or the nearly the same settings in 2 different menus when they switched the whole control panel. 
image

**Comment by Miepee** [comment]
Does the clipboard icon change, if you change that setting to "Hell"?

**Comment by ThanatosGit** [comment]
image
image

Doesn't change in light mode.

**Comment by Miepee** [comment]
Weird.
Wonder if it would be better to just ship our own icon.
Cause writing logic for
```py
if linux:
  if system_theme is not randovania_theme:
    invert_image_colors()
 elif windows:
   if randovania_theme is dark:
     invert_image_colors()
 elif macos:
   # ???
   pass
 ```
 doesn't sound like fun.
 
 
 I wouldn't be surprised if QtQuick had a proper solution to this, but I also am not keen on just rewriting everything into qtquick.

**Comment by ThanatosGit** [comment]
I switched to Windows 11. lol
image
image

**Comment by Miepee** [comment]
Gonna close this PR, as every OS coloring the icon in its own way is a nightmare.
No clue how to do it better, we probably need to provide our own icon and then recolor it based on whether dark mode gets (de)actiavted? Which also doesn't sound as nice. IDK.
Advice QT Experts welcome

**Pull request closed without merging**
