### PR TITLE
Echoes: Fix Main PB not counting towards PBs on UI

### PR DESCRIPTION
**Pull request by Miepee**
Before:
grafik

After:
grafik

### CODE REVIEW

**Comment by henriquegemignani** [comment]
Does this really cause no differences in the patcher json generated for Echoes? Or are we just missing some test? Which I wouldn't dismiss as unlikely 😅

**Comment by Miepee** [comment]
:shrug: 
I feel like we're definitely missing tests for more exotic options, but I'm pretty sure this one is fine

**Comment by henriquegemignani** [comment]
I find it really weird that adding a progression entry for the pickup causes no differences. That's the kind of thing that _should_ change how a pickup is exported and should need at least one test being changed.

**Comment by Miepee** [comment]
So I had a look at this.
I exported a game with PB set to "shuffled" before this patch, and let the factory generate a json. I also did the same for "seed_a".
Then I ran through both my game and "seed_a" after this patch and low and behold.... only "seed_a" changed it's output.
In the resources for the Main PB, it's now given 3 times for whatever reason.
```json
"resources": [
    {
        "index": 43,
        "amount": 2
    },
    {
        "index": 47,
        "amount": 1
    },
    {
        "index": 43,
        "amount": 1
    },
    {
        "index": 74,
        "amount": 57
    }
],
```
Note how index 43 is in there 2 times.

I got curious as to why my game didn't cause any change. Apparently it's because setting it to "shuffled" caused it in the RDVgame to not exist at all. So something's just really screwy there, and this approach to fixing it is probably wrong.

**Comment by Miepee** [comment]
This approach to fixing it is wrong, thus cloasing
#5410 should be merged first before reinvestigating this

**Pull request closed without merging**
