### PR TITLE
AM2R: Fix shinies being located in metroids

### PR DESCRIPTION
**Pull request by Miepee**
I encountered a shiny missile in a metroid, dont want that again.

### CODE REVIEW

**Comment by Uncle-Reggie** [comment]
Alternatively, what if a shiny missile made the Metroid shiny?

**Comment by Miepee** [comment]
Sounds neat on paper, however practically:
A) i'd need to recolor a bunch of metroid sprites which i dont want to
B) I'd need to fiddle with the draw code of metroids, which is already complex enough as-is as they're all split into multiple parts and draw each other a bit differently.

**Comment by JeffGainsNGames** [comment]
I think it's kinda funny to leave in imo

**Comment by henriquegemignani** [comment]
Is all that is happening is getting a "Shiny X" message from a metroid drop?

**Comment by Miepee** [comment]
Yup. Usually one would see the sprite too if it'd be a normal drop.

**Comment by Miepee** [comment]
All righty then.

**Pull request closed without merging**
