### PR TITLE
Fusion: correct pdf for schema, add sound settings

### PR DESCRIPTION
**Pull request by JeffGainsNGames**

### CODE REVIEW

**Comment by Miepee** [comment]
needs tests fixed

**Comment by JeffGainsNGames** [comment]
does that mean delete the world_1.json and re-run that one thing again

**Comment by Miepee** [comment]
no need to delete it, just rerun it

**Review by Miepee — APPROVED** [review]
For the next PR(s), unexplored map should be relatively easy, can just copy AM2R for most things.
Missile Limit, I'm unsure what the best way to represent them is. We probably only really need 2 (vanilla), 3 (mars), 4 (zm). gotta figure out a nice understandable name for "3"

**Pull request merged**
