### PR TITLE
Bump am2r_yams to 1.2.11

### PR DESCRIPTION
**Pull request by Miepee**
Feedback for the Dread and CS changes would be nice

### CODE REVIEW

**Review by duncathan — DISMISSED** [review]
I would rather CS items all use the generic sprite for now

**Comment by Miepee** [comment]
The dread changes are fine?

**Comment by duncathan** [comment]
yeah

**Comment by Miepee** [comment]
Should have addressed CS

**Review by henriquegemignani — APPROVED** [review]

**Pull request merged**
