### PR TITLE
Dread door lock rando

### PR DESCRIPTION
**Pull request by duncathan**

### CODE REVIEW

**Comment by steven11sjf** [comment]
Small thing but maybe change the name of sensor lock doors so it's more clear that they're phantom cloak doors? flash shift also uses "sensors" and I was confused for a second until i read the rest of the doors and figured it out.

**Comment by steven11sjf** [comment]
Also, access open doors can be changed to as well. I'd suggest defaulting to off though since it doesn't really add anything other than not needing to shoot them. 

As a side note, the order of doors in the UI seems off. I'd either organize it based on type (ie Power, Wide, Plasma, Wave, Missile, Super, ...) or alphabetically.

**Comment by duncathan** [comment]
> Small thing but maybe change the name of sensor lock doors so it's more clear that they're phantom cloak doors? flash shift also uses "sensors" and I was confused for a second until i read the rest of the doors and figured it out.

it's the official name

**Comment by duncathan** [comment]
> Also, access open doors can be changed to as well. I'd suggest defaulting to off though since it doesn't really add anything other than not needing to shoot them.
> 
> As a side note, the order of doors in the UI seems off. I'd either organize it based on type (ie Power, Wide, Plasma, Wave, Missile, Super, ...) or alphabetically.

the order isn't actually related to any of these changes. that's something for another pr if there's concerns

**Pull request merged**
