### PR TITLE
Move game specific zebeth ui

### PR DESCRIPTION
**Pull request by ThanatosGit**
@UltiNaruto I think goal, hints and patches are unused? Would be nice if you could later either add the unused ui files or remove them.

### CODE REVIEW

**Comment by UltiNaruto** [comment]
> @UltiNaruto I think goal, hints and patches are unused? Would be nice if you could later either add the unused ui files or remove them.

Goal is used :
image

As for hints, I got some plans to use it for Tourian Keys.
Same goes for patches.
But yeah hints and patches aren't used yet.

**Comment by henriquegemignani** [comment]
I would rather unused files to not be in the main branch. Keep a branch with the files so you can easily grab them.

**Comment by UltiNaruto** [comment]
so remove the ui for patches and hints, right?

**Comment by Miepee** [comment]
yes

**Comment by UltiNaruto** [comment]
should I wait till this PR is merged or should I go ahead and remove the files?

**Comment by ThanatosGit** [comment]
> But yeah hints and patches aren't used yet.

Oops, I think what I wanted to say was hints, patches and game export.

Removed the 3 files now.

**Comment by UltiNaruto** [comment]
No problem

**Comment by Miepee** [comment]
test

**Comment by Miepee** [comment]
test

**Comment by Miepee** [comment]
Hello World

**Pull request merged**
