### PR TITLE
Dread: Add Short boost as a Trick

### PR DESCRIPTION
**Pull request by SFJucelino**
1) Added Short Boost as a Trick.
~~2) Added a path that requires SSC and Short Boost in Screw Attack room.~~
2) Updated trick description and added link to tutorial/showcase where needed.

### CODE REVIEW

**Review by XenoWars — APPROVED** [review]
When it comes time to add implementations for it, I would suggest putting in all the ones you can think of, region by region.

**Comment by XenoWars** [comment]
Would like another opinion on the extensions of the trick descriptions. I personally do not feel they are necessary and could just have the link to a vod added to what was already there.

**Comment by henriquegemignani** [comment]
> Would like another opinion on the extensions of the trick descriptions. I personally do not feel they are necessary and could just have the link to a vod added to what was already there.

I don't trust links to external resources to stay up long term. (This is also a problem I have with link to videos in the db, but for _usages_ of a trick it's more necessary).
The only link I'd like with trick descriptions would be to a community wiki.

**Review by duncathan — CHANGES_REQUESTED** [review]
Please remove the video links from the trick descriptions for the time being. We can discuss them in a separate PR if desired

**Comment by duncathan** [comment]
if we want to add short boost as a trick we can do so in a PR that does only that

**Pull request closed without merging**
