### PR TITLE
Change tracker to use Nodes instead of Areas

### PR DESCRIPTION
**Pull request by ThanatosGit**
The best description for this PR: 
"I tried to make it less broken."

### CODE REVIEW

**Comment by Miepee** [comment]
Dread and Echoes got fixed, so it indeed is less broken :)

You also forgot a changelog entry btw

**Comment by ThanatosGit** [comment]
> Dread and Echoes got fixed, so it indeed is less broken :)

I thought it was Dread and Prime? But Prime and Echoes works for me in 6.2.0.
Was it a specific preset setting? (Which games got fixed is good to know for a changelog entry)

**Comment by Miepee** [comment]
you're correct, was dread and prime1. It happened already on starter preset, not sure whether there was some setting that would allow it *not* to crash.

**Comment by ThanatosGit** [comment]
In 6.2.0 the April Fools and Moderate Challenge preset works. Starter does not.

**Review by henriquegemignani — APPROVED** [review]

**Pull request merged**
