### PR TITLE
Make preset_generation.ui game-neutral

### PR DESCRIPTION
**Pull request by Shaleblade**
The generation tab of the preset editor had a lot of Echoes-specific language in it, which this removes. (Not touching the trick editor page, since Dark wanted that to be game-specific and I don't know how to do that.)

### CODE REVIEW

**Comment by Miepee** [comment]
please post a screenshot of the changed text

**Comment by henriquegemignani** [comment]
Add changelog :D

**Comment by Shaleblade** [comment]
> please post a screenshot of the changed text

image
image
image

**Review by Miepee — APPROVED** [review]

**Comment by Shaleblade** [comment]
> Add changelog :D

OK, I think I did that correctly(?)

**Pull request merged**
