### PR TITLE
Add Dynamo Access requirements

### PR DESCRIPTION
**Pull request by gollop**

### CODE REVIEW

**Comment by henriquegemignani** [comment]
Heya, this PR is in a weird state. Seems to have conflicts? Could you take a look please?

**Comment by gollop** [comment]
Just looks like the change log has been changed since this pull request was made.

**Comment by SpaghettiToastBook** [comment]
You can just rebase and it should be fine. Although it seems that you've deleted the branch in your repo (?)

**Comment by SpaghettiToastBook** [comment]
Merged manually.

**Pull request closed without merging**
