### PR TITLE
Multi-pickup generator settings no longer experimental

### PR DESCRIPTION
**Pull request by toasterparty**
It's been long enough. I still hold that this is objectively better for seed diversity.

### CODE REVIEW

**Comment by duncathan** [comment]
Any particular reason to leave the preset options in?

**Comment by toasterparty** [comment]
No, but I know historically that options removed from GUI still tend to keep their settings in the preset.

**Comment by toasterparty** [comment]
@henriquegemignani I need help understanding the final failing test

**Comment by henriquegemignani** [comment]
A test das depending on the single set setting being off, as the function behaves differently with that setting enabled.
Since it's now always, the test is failing

**Comment by toasterparty** [comment]
> Since it's now always, the test is failing

I'm not sure how you came up with the expected data for the original implementation. It sounds like I need to do that again for the new output.

**Comment by toasterparty** [comment]
Generator Function - https://github.com/randovania/randovania/blob/2d4925641e657a8ab2e7250769335abefde51e2b/randovania/generator/filler/pickup_list.py#L168-L174

Test - https://github.com/randovania/randovania/blob/2d4925641e657a8ab2e7250769335abefde51e2b/test/generator/filler/test_pickup_list.py#L119-L172

**Review by henriquegemignani — APPROVED** [review]

**Pull request merged**
