### PR TITLE
Dread: Cataris Revision Part 2

### PR DESCRIPTION
**Pull request by XenoWars**
This revision goes over the entire EMMI Zone and up to the Artaria Transport, renaming events and other nodes, and adding other methods to trickless connection and some tricks. Pretty much every room is affected within the EMMI Zone and between Green EMMI Introduction Access and Transport to Artaria.

### CODE REVIEW

**Comment by henriquegemignani** [comment]
You don't have to put the full event name as the node name, especially if part of the event name is the area name.

**Comment by XenoWars** [comment]
Is it really a problem though? I did that for most of Burenia and Dairon already, and I personally feel it makes it easier to tell exactly what the event is at a glance, especially for those who dont know the rooms very well.

**Comment by henriquegemignani** [comment]
> Is it really a problem though? I did that for most of Burenia and Dairon already, and I personally feel it makes it easier to tell exactly what the event is at a glance, especially for those who dont know the rooms very well.

The resource itself will have the room name, so requirements show it.
The node is always displayed with the area name in context. In particular, most people only ever event nodes when checking the area itself in the data visualizer. So having the node include the area name is just harmful by being redundant.

**Comment by XenoWars** [comment]
I did all of them (I think) except the ones in Z-57 Heat Room West (Left) cause those blobs do need extra details to tell them apart

**Review by henriquegemignani — APPROVED** [review]

**Pull request merged**
