### PR TITLE
Place restrictions on names for Sessions and Worlds

### PR DESCRIPTION
**Pull request by henriquegemignani**

### CODE REVIEW

**Review by duncathan — APPROVED** [review]
looks good. I like the new text prompt class. maybe in the future we can use it for things like renaming regions/areas in the db

**Comment by henriquegemignani** [comment]
> looks good. I like the new text prompt class. maybe in the future we can use it for things like renaming regions/areas in the db

I changed everything that was using QInputDialog and async_dialog. I bet the editor stuff is using `QInputDialog.getText` which is a blocking call.

**Comment by duncathan** [comment]
> > looks good. I like the new text prompt class. maybe in the future we can use it for things like renaming regions/areas in the db
> 
> I changed everything that was using QInputDialog and async_dialog. I bet the editor stuff is using `QInputDialog.getText` which is a blocking call.

I'm not even sure if we have a way to rename areas and regions tbh, I only know for sure we can rename nodes

**Comment by Miepee** [comment]
> I'm not even sure if we have a way to rename areas and regions tbh

Areas should be renamable, if a bit buggy, AFAIK no way to rename regions

**Pull request merged**
