### PR TITLE
Database adjustments

### LINKED ISSUE #271: Scan Dash to Temple Security Access in Hive Temple should be Hypermode

### PR DESCRIPTION
**Pull request by SpaghettiToastBook**
Fixes #271.

The method to get the Main Research item with only Morph+Spider was removed, as no one seems to know what it is.

### CODE REVIEW

**Comment by henriquegemignani** [comment]
Since you've changed the Hazing Cliff requirements (was there really no
issue for that? dang, I've known that for ages already), I'd like to
mention that there's some places that lists Light Beam that also expects
some ammo, like Quadraxis.

**Comment by SpaghettiToastBook** [comment]
I guess the Quadraxis requirements expect charged Light Beam, then?
I'll look over the temple bosses' requirements later.

**Comment by SpaghettiToastBook** [comment]
I'll reopen this later,

**Comment by henriquegemignani** [comment]
At least for Quad, I imagine it expects you to have enough ammo to shoot charged light beams on enough things during the battle.

**Pull request closed without merging**
