### PR TITLE
Updated randovania/data/binary_date/.gitignore

### PR DESCRIPTION
**Pull request by UltiNaruto**

### CODE REVIEW

**Comment by henriquegemignani** [comment]
These _extra files no longer exist. Could you remove them please?

**Comment by UltiNaruto** [comment]
aren't they generated when creating a release?

**Comment by henriquegemignani** [comment]
the `.bin`, yes.
The `_extra.json` used to be, but now it's all inside the .bin

**Comment by UltiNaruto** [comment]
oh ok I'll fix it then

**Pull request merged**
