### PR TITLE
Am2r: Add tileset and background rotation

### PR DESCRIPTION
**Pull request by Miepee**
Only merge after yams bump please.
grafik

### CODE REVIEW

**Comment by Miepee** [comment]
No idea why that other test fails :cry:

**Comment by Miepee** [comment]
Doing some debugging, for some reason on type->vanilla / full->vanilla, the `_on_music_option_changed` is never even triggered. no idea how.

**Comment by Miepee** [comment]
After trial and error: *Something* in the UI file causes the test to fail. No idea what.

**Comment by Miepee** [comment]
If either of the `tileset_rotation_spinner_max` or `background_rotation_spinner_max` items is in the UI file, it causes the other test to fail.

**Comment by Miepee** [comment]
Seems to be specifically, if they are in the layout.

**Comment by Miepee** [comment]
Fixed the test.

**Review by dyceron — APPROVED** [review]
Lgtm

**Pull request merged**
