### PR TITLE
AM2R: Add liquid info as extra data

### PR DESCRIPTION
**Pull request by Miepee**

### CODE REVIEW

**Review by JeffGainsNGames — COMMENTED** [review]
Is Liquid level drawn distance X from the top of the sceen, so bigger # = lower?

**Comment by Miepee** [comment]
distance y, but yes
The exception is level 0, which means disabled

**Comment by JeffGainsNGames** [comment]
X was just a dumby variable, not refering to X,Y

Also what is should_move_horizontally?

**Comment by Miepee** [comment]
whether the liquid is still, or slowly moves on the horizontal axis
Example room where you can see it very clearly is water turbine station vs inner alpha nest south

**Review by JeffGainsNGames — APPROVED** [review]

**Pull request merged**
