### PR TITLE
Add Stream-friendly variants for Game Art autotrackers

### PR DESCRIPTION
**Pull request by SchwartzGandhi**

### CODE REVIEW

**Comment by JeffGainsNGames** [comment]
add screenshots will help reviews

**Comment by SchwartzGandhi** [comment]
Prime 1
image
Echoes
image

**Comment by duncathan** [comment]
are these for anything in particular? I really don't want to clutter the auto tracker layout options even further if we don't need to

**Comment by SchwartzGandhi** [comment]
Currently there is just the pixel variant of the stream friendly trackers, this is just to give people the option to chose between the two.
If anything, I'd say the tracker layouts would be more cluttered without these since there wouldn't be equal formats for both game and pixel art.

**Comment by duncathan** [comment]
> Currently there is just the pixel variant of the stream friendly trackers, this is just to give people the option to chose between the two.

Yes, but why? These layouts were only added to make the CGC restream easier, and afaik it was an intentional decision to only include one style so that restream would look better. Has that decision changed?

> If anything, I'd say the tracker layouts would be more cluttered without these since there wouldn't be equal formats for both game and pixel art.

...what? How does adding an entry to a list that's already way too long address the problem of the list being way too long?

**Comment by SchwartzGandhi** [comment]
> These layouts were only added to make the CGC restream easier
hmm I see, I was not aware of this part. I did bring up this idea to a TO in passing and he thought it was a good idea. But if you would like me to actually ask about this, then I can.
> How does adding an entry to a list that's already way too long address the problem of the list being way too long?
Personally, I don't think the list is too long; or rather, adding this variant won't make the list any more confusing.
I know that doesn't address the core issue at hand but I do have some ideas of decluttering these layouts that I can try to work on. But that's kinda out of scope of this PR (and Miepee told me to not increase the scope of a PR lol)

**Comment by Miepee** [comment]
Fwiw heres the whole discussiom we had on this
https://discord.com/channels/914291389293027329/914294505107251231/1229417307466498101

**Comment by henriquegemignani** [comment]
No. I only want more variants after we change the tracker so _theme_ is separate from _layout_.

**Comment by duncathan** [comment]
with dark and I both disapproving I'm gonna close this

> I only want more variants after we change the tracker so theme is separate from layout.

if TOs specifically require a new layout for tournament use again I'd be ok with adding a new one but that's just about the only exception imo

**Pull request closed without merging**
