### PR TITLE
MSR - Move `boss_go` and `boss_mae_32` to the correct type in PDF

### PR DESCRIPTION
**Pull request by dyceron**
These tracks were in the wrong section.

### CODE REVIEW

**Review by Miepee — COMMENTED** [review]
What somgs are these? Since they contain the word "boss" it sounds very weird if they're in exoloration.

**Comment by dyceron** [comment]
The ambient theme that plays after defeating a metroid (briefly) or boss. After resisting to them after making this, I was having doubts on moving them since there are less than 1 miuln long each. Might just close this pr.

**Comment by Miepee** [comment]
Id rather have them as exploration than as boss music.
Im fine with listening to a short calm ambient soundtrack while exploring, but not while fighting a boss.
The alterantive is also to move htem to excluded

**Comment by dyceron** [comment]
Ok last but, both are pretty identical, but one has extra beeps in it (the classic item room theme). Maybe the other one should be moved to excluded, or just keep both in exploration anyway.

**Comment by Miepee** [comment]
Having one in excluded and one in exploration feels weird. Either both excluded or both shuffled.

**Comment by dyceron** [comment]
Then I'll just leave it as is.

**Review by Miepee — APPROVED** [review]

**Pull request merged**
