### PR TITLE
Support seed count for benchmarks

### PR DESCRIPTION
**Pull request by Miepee**

### CODE REVIEW

**Comment by henriquegemignani** [comment]
IMO no. This command is intended for the CI job and nothing else. Focus improvements in the batch generate one.

**Comment by henriquegemignani** [comment]
Actually it's a different command. But I remember there being something else wonky with this command 🤔

**Comment by Miepee** [comment]
If you remember what was wonky with this, that'd be nice to know.

**Comment by henriquegemignani** [comment]
Afaik, having to decode/encode permalinks to the json file quite so often is ridiculously slow.
The json file is meant to be preserved to re-run in the future, but it's not quite flexible/future proof enough.

**Comment by Miepee** [comment]
I realistically don't see usage above 1k at least. For most games that's already way plenty to get a good measurement.

**Review by henriquegemignani — APPROVED** [review]

**Pull request merged**
