### PR TITLE
Fix integrity checks

### PR DESCRIPTION
**Pull request by ThanatosGit**
Fix for the prime games.

Open questions:
1. Delay SM and SR as they are not stable and can be freely changed without migration? (Though I did one for Corruption).
2. ~~`test/generator/test_base_patches_factory.py` has a TODO because the connecitons looks kinda weird to me.~~
3. ~~Echoes still has the following error `Torvus Bog/Torvus Temple/Elevator Translator Scan is not a Dock Node, naming suggests it should be.` If we want to rename it, it needs a migration for `translator_requirement` dict. What would be a good new name?~~

### CODE REVIEW

**Comment by henriquegemignani** [comment]
3. is a in-room elevator that must be scanned to activate.

Maybe the integrity check should check if a node is named `{type} (to/from` instead of just starting with `type`

**Comment by ThanatosGit** [comment]
> 3. is a in-room elevator that must be scanned to activate.
> 
> Maybe the integrity check should check if a node is named `{type} (to/from` instead of just starting with `type`

I'm fine with that but woudl move that into a different PR then.

Regarding 2.: I just realised that the Elevators are really connected in this way:
```
"Temple Grounds", "Sky Temple Gateway", "Elevator to Great Temple" -> "Great Temple", "Sky Temple Energy Controller", "Save Station"

"Great Temple", "Sky Temple Energy Controller", "Elevator to Temple Grounds" -> "Temple Grounds", "Sky Temple Gateway", "Spawn Point/Front of Teleporter"
```
I change that such that the elevators are connected to each other and add it to the `dock_connection_fixes` migration?

**Comment by henriquegemignani** [comment]
The first probably doesn't matter, but the later is certainly because leaving is a one-way trip.
If you'd connect directly to the dock, logically you'd be able to take it right after you leave. (one-way elevators can make the trip back go somewhere else)

**Comment by ThanatosGit** [comment]
Where do you actually spawn in the game?
From `Temple Grounds` to `Great Temple` logically and currently you start at the `Save Station` and the connection to `Elevator to Temple Grounds` is not trivial (has a `Dark World Damage` constraint). If I change it to connect to the `Elevator to Temple Grounds`, there are lot of more constraints to reach the `Save Station` node.

Well, what's the conclusion on both of these elevators? Leave it as it is?

**Comment by henriquegemignani** [comment]
In both cases, the answer is "depends". The spawn point of an area in Echoes changes depending on the active layers in the room. 

For Sky Temple Energy Controller, the game does some jank to try to spawn you in the elevator or the save station depending if you're coming from the elevator or if you loaded a save. In either case the dark damage there is small enough if that much damage matters, somewhere else will break harder. So where it is doesn't matter much.

For Sky Temple Gateway it also depends on whether the gate has been opened, but it's not that different. But the important thing is that the portal is just not there, even if you take a portal from elsewhere.

**Comment by ThanatosGit** [comment]
That sounds to me that I better leave it untouched. I mean, the elevators were always connected to the default node, so it wont't change anything if I'm not mistaken here.

**Comment by henriquegemignani** [comment]
@toasterparty Do you have opinions on renaming the Elevator nodes in Prime 1?

**Comment by toasterparty** [comment]
No

**Comment by henriquegemignani** [comment]
"No" as in no preferences, or "No" as in "don't do that"?

**Comment by toasterparty** [comment]
No opinion. Change away

**Review by henriquegemignani — APPROVED** [review]

**Pull request merged**
