### PR TITLE
Add xdg_assets to spec

### PR DESCRIPTION
**Pull request by flibitijibibo**
Put this in the root for now, so we don't have to fuss with the flatpak yml more. TODO: Make this Linux-only!

### CODE REVIEW

**Comment by henriquegemignani** [comment]
`.spec` files are python files, you can just do an `if is_linux`:

**Comment by flibitijibibo** [comment]
Probably should have actually checked how Python does this... can you tell I'm not a scripts guy :P

Moved the xdg_assets line to a platform.system check.

**Comment by henriquegemignani** [comment]
It's missing an `import platform` at the top.

**Comment by flibitijibibo** [comment]
PyInstaller was giving me a bit of sass about the data type, this should be fixed now. (11 years and 80 games and it's today that I finally learn Python, woops)

**Review by henriquegemignani — APPROVED** [review]

**Pull request merged**
