### PR TITLE
Fix Tracker for not-Echoes

### PR DESCRIPTION
**Pull request by henriquegemignani**

### CODE REVIEW

**Review by duncathan — DISMISSED** [review]
I'd rather at *least* put this in a dedicated function and calling it if game is echoes rather than returning early if it isn't

**Comment by henriquegemignani** [comment]
I don't want to spend any brainpower fixing this.

**Comment by Miepee** [comment]
`# TODO`? :stuck_out_tongue_closed_eyes:

**Comment by duncathan** [comment]
if nothing else you *need* to slap a FIXME comment on it lol

**Comment by henriquegemignani** [comment]
> I'd rather at _least_ put this in a dedicated function and calling it if game is echoes rather than returning early if it isn't

Eh, it's already called `update_translator_gates`.

**Comment by henriquegemignani** [comment]
I'm merging because the tracker is broken otherwise

**Comment by ThanatosGit** [comment]
> I'm merging because the tracker is broken otherwise

Then you need to dismiss requested changes.

**Comment by henriquegemignani** [comment]
> > I'm merging because the tracker is broken otherwise
> 
> Then you need to dismiss requested changes.

Reviews don't normally block merging, weird.

**Pull request merged**
