### PR TITLE
added speedkeep for ghav spin tower

### PR DESCRIPTION
**Pull request by steven11sjf**
- set to expert speed booster conservation, probably only has a 3-4 frame window to land it
- added a video for it as well

https://www.youtube.com/watch?v=17MNab3SmMc

### CODE REVIEW

**Comment by Tyranisaur** [comment]
Needs changelog entry, otherwise looks good.

**Review by XenoWars — CHANGES_REQUESTED** [review]
I wouldn't know why tests are failing, but it looks fine to me. Just needs the changelog as said

**Comment by steven11sjf** [comment]
ok, added changelog and rebased on main. maybe that will fix tests? 

it's weird that they're failing on multiworld stuff though. have they failed on other PRs?

**Review by Tyranisaur — APPROVED** [review]

**Comment by Miepee** [comment]
IIRC the failing test was the usual "something leaks in multiworld which causes a random test fail".

**Pull request merged**
