### PR TITLE
Prime3: Add Landing Site quick fill option

### LINKED ISSUE #2335: Prime 3: add Quick Fill option for starting location with all ship landing sites in the game
Like the title says, but maybe we could go a step further. Currently, Quick Fill options are buttons that automatically fill in choices in the list below, right? What if, at least for Prime 3 since it has multiple landing sites, that was made into a tick option itself so you could have save stations, landing sites or both?

### PR DESCRIPTION
**Pull request by Miepee**
Fixes #2335

### CODE REVIEW

**Comment by dyceron** [comment]
Could you add a screenshot of this?

**Comment by Miepee** [comment]
grafik

**Review by dyceron — CHANGES_REQUESTED** [review]
This is missing some non excluded Landing Sites.

**Comment by Miepee** [comment]
Which ones?

**Comment by dyceron** [comment]
Reference this list https://metroid.fandom.com/wiki/List_of_Landing_Sites

**Comment by Miepee** [comment]
I did
I excluded G.F.S Olympus, All the Seeds, and Phaaze.
See the explanation blurb at the top

**Comment by dyceron** [comment]
The blurb does not mention the ones you have to unlock. Regardless, it'd be future proofing in case we ever get an option to start at those landing sites which need to be unlocked first.

**Comment by Miepee** [comment]
> The blurb does not mention the ones you have to unlock. 

1. Because the DB doesn't even mark those as potential starting areas, so you can't even manually select them. Notice how Bryyo's Hangar Bay, or Elysia's Federation Landing Site are completely missing as a room.
grafik
grafik

2. If those areas mark their landing sites as viable starts, then they will be automatically checked here as well.

**Comment by dyceron** [comment]
Norion Cargo Dock B needs to be removed then since that one has to be unlocked first

**Review by dyceron — APPROVED** [review]

**Pull request merged**
