### PR TITLE
Add vertical dock information

### PR DESCRIPTION
**Pull request by JeffGainsNGames**
Excluded from this PR:
- one way paths (BG2 shinespark, Tower Interior)
- Tower exterior

### CODE REVIEW

**Comment by Miepee** [comment]
Thoth is missing

**Review by Miepee — COMMENTED** [review]
HS Exterior -> Arachnus save station door is wrong
Varia Chamber Access -> Left water pipe dock is wrong
South east gamma nest in tower is missing



Looks good otherwise. we should probably better document the ones who're missing tho, so that it isn't needed to crawl through the whole DB for them.

**Comment by JeffGainsNGames** [comment]
Will make corrections. I can add a TODO to the remaining docks, but honestly there aren't many vertical transitions in total.

**Review by Miepee — APPROVED** [review]
ty

**Pull request merged**
