### PR TITLE
Reorganize AM2Rs preset tabs

### PR DESCRIPTION
**Pull request by Miepee**
- Reorganizes am2r's preset tabs
- Makes flipping/mirrored game not unsupported anymore

grafik
grafik
grafik
grafik

### CODE REVIEW

**Comment by JeffGainsNGames** [comment]
Approve from a GUI view but tests fail

**Comment by JeffGainsNGames** [comment]
Did you test generate some seeds with various settings to make sure gen/export worked well?

**Comment by Miepee** [comment]
I tested that all settings that I touched save and read properly.
I did not test generation, as generation wasn't touched.

**Review by JeffGainsNGames — APPROVED** [review]

**Comment by JeffGainsNGames** [comment]
> I did not test generation, as generation wasn't touched.
that was just my dumb way of asking/checking if things saved properly

**Pull request merged**
