### PR TITLE
Fix foldable being cut off

### LINKED ISSUE #4617: "Expandable widgets" sometimes chop off text
IDK if this is potentially linux related or something else. I went through the whole GUI and this was the only place where i could find them
grafik
These should say `Charge Combos` and `Energy Tanks` but look like `Charoe Combos` and `Eneroy Tanks` due to the chopped of `g`

### PR DESCRIPTION
**Pull request by Miepee**
Dunno if increasing the height is really the right fix for it, but it does work.
Fixes #4617 
grafik

### CODE REVIEW

**Comment by henriquegemignani** [comment]
Does less height work, like 25?

**Comment by Miepee** [comment]
Barely, depending on the installed font and/or other characters, this might clip
grafik

**Comment by Miepee** [comment]
This is with 28, doesn't seem like it'd cause any issues. If wanted I can change it to this
grafik

**Comment by henriquegemignani** [comment]
If things look ugly we can revisit.

**Review by henriquegemignani — APPROVED** [review]

**Pull request merged**
