### PR TITLE
Update the inventory of offline worlds

### PR DESCRIPTION
**Pull request by henriquegemignani**

### CODE REVIEW

**Comment by ThanatosGit** [comment]
I'm getting too tired to read it carefully but what would like to ask / comes to my mind: Does this work with non-required mains? Like flash shift is granted because of a flash shift upgrade was sent as item?

**Comment by henriquegemignani** [comment]
It'll respect whatever setting is present in their setting, as that's how `PickupEntry.resource_gain` works.

**Comment by ThanatosGit** [comment]
Hmmm I tried that with two dread worlds and only debug connectors but the flash shift did not show up in the inventory.
Though it's a little bit awkward to test because the receiver first needs to have a non null inventory.

**Review by duncathan — APPROVED** [review]

**Comment by henriquegemignani** [comment]
> Hmmm I tried that with two dread worlds and only debug connectors but the flash shift did not show up in the inventory when granting flash shift upgrade. Though it's a little bit awkward to test because the receiver first needs to have a non null inventory.

Hm... I wonder where the issue could be.

This isn't perfect, but as long as it doesn't cause issues I'm fine with a little weirdness. We can fix things later.

**Pull request merged**
